package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	// Настройка конфигурации.
	cfg := &packages.Config{
		Mode:  packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes,
		Tests: false,
		Fset:  token.NewFileSet(),
		// заставляет парсер сохранять комментарии
		ParseFile: func(fset *token.FileSet, filename string, src []byte) (*ast.File, error) {
			return parser.ParseFile(fset, filename, src, parser.ParseComments)
		},
	}

	fmt.Println("Сканирую пакеты...")
	// parser.ParseDir устарел
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		log.Fatal(err)
	}

	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			fmt.Printf("Ошибки в пакете %s: %v\n", pkg.PkgPath, pkg.Errors)
			continue
		}
		processPackage(pkg)
	}
}

func hasResetComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.Contains(c.Text, "// generate:reset") {
			return true
		}
	}
	return false
}

func processPackage(pkg *packages.Package) {
	var buf bytes.Buffer
	hasMatches := false

	// Перебираем файлы в пакете
	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			// Ищем объявления TYPE
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			// Проверяем наличие комментария
			if !hasResetComment(genDecl.Doc) {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				if !hasMatches {
					buf.WriteString(fmt.Sprintf("// Code generated by reset-gen. DO NOT EDIT.\npackage %s\n\n", pkg.Name))
					hasMatches = true
				}

				structName := typeSpec.Name.Name
				buf.WriteString(fmt.Sprintf("func (s *%s) Reset() {\n", structName))

				// Генерация логики для каждого поля
				for _, field := range structType.Fields.List {
					for _, name := range field.Names {
						genFieldReset(&buf, name.Name, field.Type)
					}
				}

				buf.WriteString("}\n\n")
			}
		}
	}

	if hasMatches {
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			fmt.Printf("Ошибка форматирования: %v\n", err)
			formatted = buf.Bytes()
		}

		dir := filepath.Dir(pkg.GoFiles[0])
		outputPath := filepath.Join(dir, "reset.gen.go")
		os.WriteFile(outputPath, formatted, 0644)
		fmt.Printf("Сгенерирован файл: %s\n", outputPath)
	}
}

// genFieldReset записывает логику сброса в зависимости от типа поля
func genFieldReset(buf *bytes.Buffer, fieldName string, fieldType ast.Expr) {
	switch t := fieldType.(type) {
	case *ast.ArrayType:
		// Правило: слайсы обрезаются, но не зануляются
		buf.WriteString(fmt.Sprintf("\ts.%s = s.%s[:0]\n", fieldName, fieldName))

	case *ast.MapType:
		// Правило: мапы очищаются через clear()
		buf.WriteString(fmt.Sprintf("\tclear(s.%s)\n", fieldName))

	case *ast.StarExpr:
		// Правило: не nil указатели сбрасывают свои значения
		buf.WriteString(fmt.Sprintf("\tif s.%s != nil {\n\t\ts.%s.Reset()\n\t}\n", fieldName, fieldName))

	case *ast.Ident:
		// Примитивы (int, string, bool) или вложенные структуры в том же пакете
		if isPrimitive(t.Name) {
			buf.WriteString(fmt.Sprintf("\ts.%s = %s\n", fieldName, getZeroValue(t.Name)))
		} else {
			// Reset() должен быть реализован для вложенных структур
			buf.WriteString(fmt.Sprintf("\ts.%s.Reset()\n", fieldName))
		}

	case *ast.SelectorExpr:
		// Другие пакеты (например, time.Time)
		// Вариантов типа бесконечно много, предполагаю что у них свой Reset
		buf.WriteString(fmt.Sprintf("\ts.%s.Reset()\n", fieldName))

	default:
		// Универсальный сброс к zero value для всего остального
		buf.WriteString(fmt.Sprintf("\ts.%s = *new(%s)\n", fieldName, "interface{}"))
	}
}

func isPrimitive(name string) bool {
	switch name {
	case "bool", "string", "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"byte", "rune", "float32", "float64", "complex64", "complex128":
		return true
	}
	return false
}

func getZeroValue(name string) string {
	switch name {
	case "bool":
		return "false"
	case "string":
		return `""`
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "byte", "rune":
		return "0"
	case "float32", "float64":
		return "0.0"
	default:
		return "nil"
	}
}
