// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_urlstore.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockURLStore is a mock of URLStore interface.
type MockURLStore struct {
	ctrl     *gomock.Controller
	recorder *MockURLStoreMockRecorder
	isgomock struct{}
}

// MockURLStoreMockRecorder is the mock recorder for MockURLStore.
type MockURLStoreMockRecorder struct {
	mock *MockURLStore
}

// NewMockURLStore creates a new mock instance.
func NewMockURLStore(ctrl *gomock.Controller) *MockURLStore {
	mock := &MockURLStore{ctrl: ctrl}
	mock.recorder = &MockURLStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLStore) EXPECT() *MockURLStoreMockRecorder {
	return m.recorder
}

// AddURL mocks base method.
func (m *MockURLStore) AddURL(id string, longURL any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddURL", id, longURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddURL indicates an expected call of AddURL.
func (mr *MockURLStoreMockRecorder) AddURL(id, longURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddURL", reflect.TypeOf((*MockURLStore)(nil).AddURL), id, longURL)
}

// GetURL mocks base method.
func (m *MockURLStore) GetURL(shortURL string) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", shortURL)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockURLStoreMockRecorder) GetURL(shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockURLStore)(nil).GetURL), shortURL)
}
